# One-click launcher: Python Agent + Java backend + Vue frontend.
# Keep this file ASCII-only so Windows PowerShell 5.1 can parse it without a UTF-8 BOM.
$ErrorActionPreference = 'Stop'

$RootDir = $PSScriptRoot
$AgentDir = Join-Path $RootDir 'lingXi-agent'
$JavaDir = Join-Path $RootDir 'dkd-parent'
$VueDir = Join-Path $RootDir 'lingXi-vue'
$AgentEnvFile = Join-Path $AgentDir '.env'

function ConvertFrom-DotEnvValue {
    param([AllowEmptyString()][string]$RawValue)

    $value = $RawValue.Trim()
    if ($value.Length -ge 2) {
        $first = $value.Substring(0, 1)
        $last = $value.Substring($value.Length - 1, 1)
        if (($first -eq '"' -and $last -eq '"') -or
            ($first -eq "'" -and $last -eq "'")) {
            return $value.Substring(1, $value.Length - 2)
        }
    }

    return ($value -replace '\s+#.*$', '').Trim()
}

function Get-DotEnvValue {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Name
    )

    if (-not (Test-Path -LiteralPath $Path)) {
        return $null
    }

    $found = $null
    foreach ($line in [System.IO.File]::ReadAllLines($Path)) {
        if ($line -match '^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$' -and
            $matches[1] -eq $Name) {
            $found = ConvertFrom-DotEnvValue -RawValue $matches[2]
        }
    }
    return $found
}

function New-AgentServiceKey {
    $bytes = New-Object byte[] 32
    $generator = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $generator.GetBytes($bytes)
    }
    finally {
        $generator.Dispose()
    }

    return [Convert]::ToBase64String($bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')
}

function Save-AgentServiceKey {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$ServiceKey
    )

    $lines = New-Object 'System.Collections.Generic.List[string]'
    if (Test-Path -LiteralPath $Path) {
        foreach ($line in [System.IO.File]::ReadAllLines($Path)) {
            [void]$lines.Add($line)
        }
    }

    $updated = $false
    for ($index = 0; $index -lt $lines.Count; $index++) {
        if ($lines[$index] -match '^\s*(?:export\s+)?AGENT_SERVICE_API_KEY\s*=') {
            $lines[$index] = 'AGENT_SERVICE_API_KEY=' + $ServiceKey
            $updated = $true
        }
    }

    if (-not $updated) {
        if ($lines.Count -gt 0 -and -not [string]::IsNullOrWhiteSpace($lines[$lines.Count - 1])) {
            [void]$lines.Add('')
        }
        [void]$lines.Add('# Shared secret generated by start.ps1; do not commit this file.')
        [void]$lines.Add('AGENT_SERVICE_API_KEY=' + $ServiceKey)
    }

    $encoding = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllLines($Path, $lines.ToArray(), $encoding)
}

function Initialize-AgentServiceKey {
    param([Parameter(Mandatory = $true)][string]$EnvFile)

    $processCanonical = if ($env:AGENT_SERVICE_API_KEY) {
        $env:AGENT_SERVICE_API_KEY.Trim()
    } else { $null }
    $processLegacy = if ($env:SERVICE_API_KEY) {
        $env:SERVICE_API_KEY.Trim()
    } else { $null }

    if ($processCanonical -and $processLegacy -and
        $processCanonical -cne $processLegacy) {
        throw 'AGENT_SERVICE_API_KEY and SERVICE_API_KEY conflict in the process environment.'
    }

    $fileCanonical = Get-DotEnvValue -Path $EnvFile -Name 'AGENT_SERVICE_API_KEY'
    $fileLegacy = Get-DotEnvValue -Path $EnvFile -Name 'SERVICE_API_KEY'
    if ($fileCanonical -and $fileLegacy -and $fileCanonical -cne $fileLegacy) {
        throw 'AGENT_SERVICE_API_KEY and SERVICE_API_KEY conflict in lingXi-agent\.env.'
    }

    $serviceKey = $processCanonical
    if (-not $serviceKey) { $serviceKey = $processLegacy }
    if (-not $serviceKey) { $serviceKey = $fileCanonical }
    if (-not $serviceKey) { $serviceKey = $fileLegacy }

    if (-not $serviceKey) {
        $serviceKey = New-AgentServiceKey
        Save-AgentServiceKey -Path $EnvFile -ServiceKey $serviceKey
        Write-Host '      Generated a local shared Agent service key.' -ForegroundColor Green
    }
    elseif ($serviceKey.Length -lt 32 -or
            $serviceKey -match '^(replace-with|change-?me|your-)') {
        throw 'AGENT_SERVICE_API_KEY must be a non-placeholder secret of at least 32 characters.'
    }

    # Child processes inherit this value. Never put it in command-line arguments.
    $env:AGENT_SERVICE_API_KEY = $serviceKey
}

function Test-TcpPort {
    param(
        [Parameter(Mandatory = $true)][string]$HostName,
        [Parameter(Mandatory = $true)][int]$Port,
        [int]$TimeoutMilliseconds = 500
    )

    $client = New-Object System.Net.Sockets.TcpClient
    try {
        $pending = $client.BeginConnect($HostName, $Port, $null, $null)
        if (-not $pending.AsyncWaitHandle.WaitOne($TimeoutMilliseconds)) {
            return $false
        }
        $client.EndConnect($pending)
        return $true
    }
    catch {
        return $false
    }
    finally {
        $client.Dispose()
    }
}

function Test-HttpReady {
    param([Parameter(Mandatory = $true)][string]$Uri)

    try {
        $response = Invoke-WebRequest -Uri $Uri -UseBasicParsing -TimeoutSec 2
        return $response.StatusCode -ge 200 -and $response.StatusCode -lt 300
    }
    catch {
        return $false
    }
}

function Wait-HttpReady {
    param(
        [Parameter(Mandatory = $true)][string]$Uri,
        [Parameter(Mandatory = $true)][int]$TimeoutSeconds,
        [Parameter(Mandatory = $true)][string]$ServiceName
    )

    $deadline = [DateTime]::UtcNow.AddSeconds($TimeoutSeconds)
    while ([DateTime]::UtcNow -lt $deadline) {
        if (Test-HttpReady -Uri $Uri) {
            return
        }
        Start-Sleep -Milliseconds 500
    }
    throw "$ServiceName did not become ready within $TimeoutSeconds seconds. Check its terminal tab."
}

function Wait-TcpPort {
    param(
        [Parameter(Mandatory = $true)][string]$HostName,
        [Parameter(Mandatory = $true)][int]$Port,
        [Parameter(Mandatory = $true)][int]$TimeoutSeconds,
        [Parameter(Mandatory = $true)][string]$ServiceName
    )

    $deadline = [DateTime]::UtcNow.AddSeconds($TimeoutSeconds)
    while ([DateTime]::UtcNow -lt $deadline) {
        if (Test-TcpPort -HostName $HostName -Port $Port) {
            return
        }
        Start-Sleep -Milliseconds 500
    }
    throw "$ServiceName did not listen on port $Port within $TimeoutSeconds seconds. Check its terminal tab."
}

function Resolve-MavenCommand {
    $command = Get-Command 'mvn.cmd' -ErrorAction SilentlyContinue | Select-Object -First 1
    if (-not $command) {
        $command = Get-Command 'mvn' -ErrorAction SilentlyContinue | Select-Object -First 1
    }
    if ($command) {
        return $command.Source
    }

    if ($env:MAVEN_HOME) {
        $mavenHomeCommand = Join-Path $env:MAVEN_HOME 'bin\mvn.cmd'
        if (Test-Path -LiteralPath $mavenHomeCommand) {
            return $mavenHomeCommand
        }
    }

    $wrapperCache = Join-Path $env:USERPROFILE '.m2\wrapper\dists'
    if (Test-Path -LiteralPath $wrapperCache) {
        $cachedCommand = Get-ChildItem -LiteralPath $wrapperCache -Filter 'mvn.cmd' -Recurse -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First 1
        if ($cachedCommand) {
            return $cachedCommand.FullName
        }
    }

    throw 'Maven was not found. Install Maven or configure MAVEN_HOME/PATH.'
}

function Resolve-PythonCommand {
    $venvPython = Join-Path $AgentDir '.venv\Scripts\python.exe'
    if (Test-Path -LiteralPath $venvPython) {
        return $venvPython
    }

    $command = Get-Command 'python.exe' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($command) {
        return $command.Source
    }

    throw 'Python was not found. Create lingXi-agent\.venv or configure Python PATH.'
}

function Resolve-WindowsTerminalCommand {
    $command = Get-Command 'wt.exe' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($command) {
        return $command.Source
    }

    throw 'Windows Terminal (wt.exe) was not found.'
}

function Start-LingXiTerminalTab {
    param(
        [Parameter(Mandatory = $true)][string]$Title,
        [Parameter(Mandatory = $true)][string]$WorkingDirectory,
        [Parameter(Mandatory = $true)][string]$CommandLine
    )

    $terminalArguments = '-w LingXiServices new-tab --title "{0}" --suppressApplicationTitle --startingDirectory "{1}" cmd.exe /k {2}' -f `
        $Title, $WorkingDirectory, $CommandLine
    Start-Process -FilePath $WindowsTerminalCommand -ArgumentList $terminalArguments
}

Write-Host '========================================' -ForegroundColor Cyan
Write-Host '  LingXi one-click launcher' -ForegroundColor Cyan
Write-Host '========================================' -ForegroundColor Cyan
Write-Host ''

try {
    $PythonCommand = Resolve-PythonCommand
    $MavenCommand = Resolve-MavenCommand
    $WindowsTerminalCommand = Resolve-WindowsTerminalCommand
    Initialize-AgentServiceKey -EnvFile $AgentEnvFile

    Write-Host '[1/3] Starting AI Agent with reload...' -ForegroundColor Yellow
    if (Test-HttpReady -Uri 'http://127.0.0.1:5000/readyz') {
        Write-Host '      Agent is already ready: http://localhost:5000' -ForegroundColor Green
    }
    else {
        if (Test-TcpPort -HostName '127.0.0.1' -Port 5000) {
            throw 'Port 5000 is occupied by an Agent that is not ready. Close that process and run start.bat again.'
        }
        $agentStartup = '"{0}" -m uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload' -f $PythonCommand
        Start-LingXiTerminalTab -Title 'LingXi AI Agent' -WorkingDirectory $AgentDir -CommandLine $agentStartup
        Wait-HttpReady -Uri 'http://127.0.0.1:5000/readyz' -TimeoutSeconds 45 -ServiceName 'AI Agent'
        Write-Host '      Agent ready: http://localhost:5000' -ForegroundColor Green
    }

    Write-Host '[2/3] Installing Java modules and starting LingXiApplication...' -ForegroundColor Yellow
    if (Test-TcpPort -HostName '127.0.0.1' -Port 8080) {
        Write-Host '      Java is already listening: http://localhost:8080' -ForegroundColor Green
    }
    else {
        $javaStartup = 'call "{0}" -pl lingXi-admin -am -DskipTests install && call "{0}" -f lingXi-admin\pom.xml -DskipTests -Dspring-boot.run.main-class=com.lingXi.LingXiApplication spring-boot:run' -f $MavenCommand
        Start-LingXiTerminalTab -Title 'LingXi Java Backend' -WorkingDirectory $JavaDir -CommandLine $javaStartup
        Wait-TcpPort -HostName '127.0.0.1' -Port 8080 -TimeoutSeconds 240 -ServiceName 'Java backend'
        Write-Host '      Java ready: http://localhost:8080' -ForegroundColor Green
    }

    Write-Host '[3/3] Starting Vue frontend...' -ForegroundColor Yellow
    $vueStartup = 'npm run dev'
    Start-LingXiTerminalTab -Title 'LingXi Vue Frontend' -WorkingDirectory $VueDir -CommandLine $vueStartup
    Write-Host '      Vue: use the URL printed in the npm window' -ForegroundColor Green

    Write-Host ''
    Write-Host '========================================' -ForegroundColor Cyan
    Write-Host '  All three start commands were launched.' -ForegroundColor Green
    Write-Host '========================================' -ForegroundColor Cyan
}
catch {
    Write-Host ''
    Write-Host ('Launcher failed: ' + $_.Exception.Message) -ForegroundColor Red
    Read-Host 'Press Enter to close this launcher window'
    exit 1
}
