-- AI 小说视频自动化工作流模块（MySQL 8.0 / utf8mb4）
-- 逻辑关联使用索引，未使用数据库外键，便于任务重试、归档和软删除。

CREATE TABLE IF NOT EXISTS ai_video_project (
  project_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '项目ID',
  project_name VARCHAR(128) NOT NULL COMMENT '项目名称',
  source_type VARCHAR(32) NOT NULL DEFAULT 'NOVEL' COMMENT '来源:NOVEL/ORIGINAL_SCRIPT',
  adaptation_mode VARCHAR(32) NOT NULL DEFAULT 'FAITHFUL' COMMENT '改编模式:FAITHFUL/ADAPTIVE',
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT '状态:DRAFT/ACTIVE/PAUSED/ARCHIVED',
  owner_user_id BIGINT NOT NULL COMMENT '所属用户ID',
  cover_url VARCHAR(1024) DEFAULT NULL COMMENT '项目封面图片URL',
  visual_style VARCHAR(255) DEFAULT NULL COMMENT '视觉风格摘要',
  style_guide_json JSON DEFAULT NULL COMMENT '全局风格、色板、摄影规则',
  default_aspect_ratio VARCHAR(16) NOT NULL DEFAULT '16:9' COMMENT '默认画幅',
  default_language VARCHAR(16) NOT NULL DEFAULT 'zh-CN' COMMENT '默认语言',
  storage_bytes BIGINT NOT NULL DEFAULT 0 COMMENT '已占用存储字节',
  estimated_cost DECIMAL(12,4) NOT NULL DEFAULT 0 COMMENT '预估成本',
  actual_cost DECIMAL(12,4) NOT NULL DEFAULT 0 COMMENT '实际成本',
  create_by VARCHAR(64) DEFAULT '' COMMENT '创建者',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64) DEFAULT '' COMMENT '更新者',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  del_flag CHAR(1) NOT NULL DEFAULT '0' COMMENT '删除标志:0存在 2删除',
  PRIMARY KEY (project_id),
  KEY idx_project_owner_status (owner_user_id, status),
  KEY idx_project_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI视频项目';

CREATE TABLE IF NOT EXISTS ai_video_chapter (
  chapter_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '章节ID',
  project_id BIGINT NOT NULL COMMENT '项目ID',
  chapter_no INT NOT NULL COMMENT '章节序号',
  chapter_title VARCHAR(255) DEFAULT NULL COMMENT '章节标题',
  source_text LONGTEXT NOT NULL COMMENT '原始小说文本',
  source_hash CHAR(64) NOT NULL COMMENT '原文SHA-256',
  word_count INT NOT NULL DEFAULT 0 COMMENT '字数',
  summary_text TEXT DEFAULT NULL COMMENT '章节摘要',
  parse_status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/RUNNING/SUCCEEDED/FAILED',
  pipeline_status VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED' COMMENT '章节流水线状态',
  current_bible_version INT NOT NULL DEFAULT 0 COMMENT '当前故事圣经版本',
  source_metadata_json JSON DEFAULT NULL COMMENT '来源文件、页码等元数据',
  create_by VARCHAR(64) DEFAULT '',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64) DEFAULT '',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  del_flag CHAR(1) NULL DEFAULT '0',
  PRIMARY KEY (chapter_id),
  UNIQUE KEY uk_chapter_project_no (project_id, chapter_no, del_flag),
  KEY idx_chapter_project_status (project_id, pipeline_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI视频章节';

CREATE TABLE IF NOT EXISTS ai_video_story_bible (
  bible_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '故事圣经ID',
  project_id BIGINT NOT NULL COMMENT '项目ID',
  chapter_id BIGINT DEFAULT NULL COMMENT '产生该版本的章节ID',
  version_no INT NOT NULL COMMENT '版本号',
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/APPROVED/DEPRECATED',
  world_setting TEXT DEFAULT NULL COMMENT '世界观',
  timeline_json JSON DEFAULT NULL COMMENT '事件时间线',
  relationship_json JSON DEFAULT NULL COMMENT '人物关系',
  immutable_facts_json JSON DEFAULT NULL COMMENT '不可修改事实',
  content_json JSON NOT NULL COMMENT '完整结构化故事圣经',
  source_reference_json JSON DEFAULT NULL COMMENT '原文引用范围',
  model_name VARCHAR(128) DEFAULT NULL COMMENT '生成模型',
  prompt_version VARCHAR(64) DEFAULT NULL COMMENT '提示词模板版本',
  create_by VARCHAR(64) DEFAULT '',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64) DEFAULT '',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  del_flag CHAR(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (bible_id),
  UNIQUE KEY uk_bible_chapter_version (chapter_id, version_no, del_flag),
  KEY idx_bible_chapter (chapter_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='版本化故事圣经';

CREATE TABLE IF NOT EXISTS ai_video_character (
  character_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '人物ID',
  project_id BIGINT NOT NULL COMMENT '项目ID',
  character_code VARCHAR(64) NOT NULL COMMENT '项目内人物编码',
  character_name VARCHAR(128) NOT NULL COMMENT '人物名称',
  aliases_json JSON DEFAULT NULL COMMENT '别名',
  gender VARCHAR(32) DEFAULT NULL COMMENT '性别',
  age_range VARCHAR(64) DEFAULT NULL COMMENT '年龄范围',
  personality_json JSON DEFAULT NULL COMMENT '性格标签',
  appearance_text TEXT DEFAULT NULL COMMENT '外观描述',
  speaking_style TEXT DEFAULT NULL COMMENT '说话风格',
  visual_prompt_base TEXT DEFAULT NULL COMMENT '固定视觉提示词',
  voice_profile_json JSON DEFAULT NULL COMMENT '音色和语速规则',
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE/ARCHIVED',
  create_by VARCHAR(64) DEFAULT '',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64) DEFAULT '',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  del_flag CHAR(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (character_id),
  UNIQUE KEY uk_character_project_code (project_id, character_code, del_flag),
  KEY idx_character_project (project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI视频人物档案';

CREATE TABLE IF NOT EXISTS ai_video_character_state (
  state_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '状态ID',
  project_id BIGINT NOT NULL COMMENT '项目ID',
  character_id BIGINT NOT NULL COMMENT '人物ID',
  chapter_id BIGINT NOT NULL COMMENT '章节ID',
  scene_id BIGINT DEFAULT NULL COMMENT '场景ID，为空表示章节状态',
  state_order INT NOT NULL DEFAULT 0 COMMENT '同章节顺序',
  outfit_asset_id BIGINT DEFAULT NULL COMMENT '服装资产ID',
  location_asset_id BIGINT DEFAULT NULL COMMENT '所在场景资产ID',
  prop_asset_ids JSON DEFAULT NULL COMMENT '携带道具资产ID列表',
  injury_text VARCHAR(1000) DEFAULT NULL COMMENT '伤势/妆容连续性',
  emotional_baseline VARCHAR(255) DEFAULT NULL COMMENT '情绪基线',
  state_json JSON DEFAULT NULL COMMENT '扩展状态',
  create_by VARCHAR(64) DEFAULT '',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64) DEFAULT '',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  del_flag CHAR(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (state_id),
  KEY idx_character_state_lookup (character_id, chapter_id, state_order),
  KEY idx_state_project_chapter (project_id, chapter_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='人物连续性状态';

CREATE TABLE IF NOT EXISTS ai_video_scene (
  scene_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '场景ID',
  project_id BIGINT NOT NULL COMMENT '项目ID',
  chapter_id BIGINT NOT NULL COMMENT '章节ID',
  scene_no INT NOT NULL COMMENT '章节内场景序号',
  scene_title VARCHAR(255) DEFAULT NULL COMMENT '场景标题',
  source_paragraph_from INT DEFAULT NULL COMMENT '原文起始段落',
  source_paragraph_to INT DEFAULT NULL COMMENT '原文结束段落',
  source_excerpt TEXT DEFAULT NULL COMMENT '原文依据',
  time_description VARCHAR(255) DEFAULT NULL COMMENT '时间',
  location_description VARCHAR(500) DEFAULT NULL COMMENT '地点',
  atmosphere VARCHAR(500) DEFAULT NULL COMMENT '氛围',
  dramatic_goal TEXT DEFAULT NULL COMMENT '戏剧目标',
  conflict_text TEXT DEFAULT NULL COMMENT '冲突',
  character_ids JSON DEFAULT NULL COMMENT '参与人物ID列表',
  scene_package_json JSON DEFAULT NULL COMMENT '场景生产包',
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/APPROVED/DEPRECATED',
  version_no INT NOT NULL DEFAULT 1 COMMENT '版本号',
  create_by VARCHAR(64) DEFAULT '',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64) DEFAULT '',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  del_flag CHAR(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (scene_id),
  UNIQUE KEY uk_scene_chapter_no_version (chapter_id, scene_no, version_no, del_flag),
  KEY idx_scene_project_chapter (project_id, chapter_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI视频场景';

CREATE TABLE IF NOT EXISTS ai_video_shot (
  shot_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '镜头ID',
  project_id BIGINT NOT NULL COMMENT '项目ID',
  chapter_id BIGINT NOT NULL COMMENT '章节ID',
  scene_id BIGINT NOT NULL COMMENT '场景ID',
  shot_no INT NOT NULL COMMENT '场景内镜头序号',
  duration_ms INT NOT NULL DEFAULT 4000 COMMENT '目标时长毫秒',
  shot_size VARCHAR(64) DEFAULT NULL COMMENT '景别',
  camera_angle VARCHAR(64) DEFAULT NULL COMMENT '机位角度',
  camera_movement VARCHAR(64) DEFAULT NULL COMMENT '运镜',
  composition_text TEXT DEFAULT NULL COMMENT '构图',
  action_text TEXT DEFAULT NULL COMMENT '动作',
  emotion_text VARCHAR(500) DEFAULT NULL COMMENT '情绪',
  dialogue_json JSON DEFAULT NULL COMMENT '对白序列',
  required_asset_ids JSON DEFAULT NULL COMMENT '所需资产ID',
  prompt_context_json JSON DEFAULT NULL COMMENT '提示词上下文',
  source_paragraph_from INT DEFAULT NULL COMMENT '原文起始段落',
  source_paragraph_to INT DEFAULT NULL COMMENT '原文结束段落',
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/APPROVED/GENERATING/COMPLETED/DEPRECATED',
  version_no INT NOT NULL DEFAULT 1 COMMENT '版本号',
  create_by VARCHAR(64) DEFAULT '',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64) DEFAULT '',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  del_flag CHAR(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (shot_id),
  UNIQUE KEY uk_shot_scene_no_version (scene_id, shot_no, version_no, del_flag),
  KEY idx_shot_chapter_scene (chapter_id, scene_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI视频分镜';

CREATE TABLE IF NOT EXISTS ai_video_asset (
  asset_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '资产ID',
  project_id BIGINT NOT NULL COMMENT '项目ID',
  chapter_id BIGINT DEFAULT NULL COMMENT '章节ID',
  scene_id BIGINT DEFAULT NULL COMMENT '场景ID',
  shot_id BIGINT DEFAULT NULL COMMENT '镜头ID',
  character_id BIGINT DEFAULT NULL COMMENT '人物ID',
  asset_code VARCHAR(96) NOT NULL COMMENT '项目内资产编码',
  asset_name VARCHAR(255) NOT NULL COMMENT '资产名称',
  asset_type VARCHAR(64) NOT NULL COMMENT '资产类型',
  asset_scope VARCHAR(32) NOT NULL DEFAULT 'PROJECT' COMMENT 'PROJECT/CHAPTER/SCENE/SHOT/CHARACTER',
  canonical_flag TINYINT NOT NULL DEFAULT 0 COMMENT '是否规范资产',
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/GENERATING/GENERATED/VALIDATING/APPROVED/REJECTED/DEPRECATED/ARCHIVED',
  version_no INT NOT NULL DEFAULT 1 COMMENT '版本号',
  source_asset_id BIGINT DEFAULT NULL COMMENT '直接来源资产',
  storage_provider VARCHAR(32) DEFAULT NULL COMMENT 'OSS/MINIO/S3',
  object_key VARCHAR(1024) DEFAULT NULL COMMENT '对象存储键',
  preview_object_key VARCHAR(1024) DEFAULT NULL COMMENT '预览对象键',
  mime_type VARCHAR(128) DEFAULT NULL COMMENT '文件类型',
  file_size BIGINT DEFAULT NULL COMMENT '文件字节数',
  content_hash CHAR(64) DEFAULT NULL COMMENT '文件SHA-256',
  width INT DEFAULT NULL COMMENT '宽度',
  height INT DEFAULT NULL COMMENT '高度',
  duration_ms INT DEFAULT NULL COMMENT '音视频时长',
  prompt_text LONGTEXT DEFAULT NULL COMMENT '正向提示词',
  negative_prompt_text TEXT DEFAULT NULL COMMENT '负向提示词',
  generation_params_json JSON DEFAULT NULL COMMENT '模型参数、seed等',
  metadata_json JSON DEFAULT NULL COMMENT '标签、授权、扩展元数据',
  approved_by VARCHAR(64) DEFAULT NULL COMMENT '批准者',
  approved_time DATETIME DEFAULT NULL COMMENT '批准时间',
  create_by VARCHAR(64) DEFAULT '',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64) DEFAULT '',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  del_flag CHAR(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (asset_id),
  UNIQUE KEY uk_asset_project_code_version (project_id, asset_code, version_no, del_flag),
  KEY idx_asset_project_type_status (project_id, asset_type, status),
  KEY idx_asset_scene_shot (scene_id, shot_id),
  KEY idx_asset_character (character_id),
  KEY idx_asset_hash (content_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI视频统一资产';

CREATE TABLE IF NOT EXISTS ai_video_asset_relation (
  relation_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '关系ID',
  project_id BIGINT NOT NULL COMMENT '项目ID',
  from_asset_id BIGINT NOT NULL COMMENT '来源资产ID',
  to_asset_id BIGINT NOT NULL COMMENT '目标资产ID',
  relation_type VARCHAR(32) NOT NULL COMMENT 'DERIVED_FROM/USES/REPLACES/REFERENCE_IMAGE',
  relation_order INT NOT NULL DEFAULT 0 COMMENT '引用顺序',
  metadata_json JSON DEFAULT NULL COMMENT '裁剪、权重、引用说明',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (relation_id),
  UNIQUE KEY uk_asset_relation (from_asset_id, to_asset_id, relation_type),
  KEY idx_asset_relation_to (to_asset_id),
  KEY idx_asset_relation_project (project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI视频资产血缘关系';

CREATE TABLE IF NOT EXISTS ai_video_provider_model (
  model_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '模型配置ID',
  provider_code VARCHAR(64) NOT NULL COMMENT '供应商编码',
  model_code VARCHAR(128) NOT NULL COMMENT '模型编码',
  model_name VARCHAR(255) NOT NULL COMMENT '模型名称',
  model_type VARCHAR(32) NOT NULL COMMENT 'LLM/IMAGE/VIDEO/VOICE/SAFETY',
  enabled_flag CHAR(1) NOT NULL DEFAULT '1' COMMENT '是否启用',
  capability_json JSON NOT NULL COMMENT '支持图生视频、参考图数量等能力',
  pricing_json JSON DEFAULT NULL COMMENT '成本规则',
  config_json JSON DEFAULT NULL COMMENT '非敏感配置',
  secret_ref VARCHAR(255) DEFAULT NULL COMMENT '密钥引用，不存明文',
  callback_config_json JSON DEFAULT NULL COMMENT '回调验签配置',
  create_by VARCHAR(64) DEFAULT '',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64) DEFAULT '',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  del_flag CHAR(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (model_id),
  UNIQUE KEY uk_provider_model (provider_code, model_code, del_flag),
  KEY idx_model_type_enabled (model_type, enabled_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI视频供应商模型配置';

CREATE TABLE IF NOT EXISTS ai_video_prompt_template (
  template_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '模板ID',
  template_code VARCHAR(96) NOT NULL COMMENT '模板编码',
  template_name VARCHAR(255) NOT NULL COMMENT '模板名称',
  task_type VARCHAR(64) NOT NULL COMMENT 'STORY_BIBLE/SCENE/SHOT/IMAGE/VIDEO/QUALITY',
  version_no INT NOT NULL COMMENT '版本号',
  system_prompt LONGTEXT DEFAULT NULL COMMENT '系统提示词',
  user_prompt_template LONGTEXT NOT NULL COMMENT '用户提示词模板',
  output_schema_json JSON DEFAULT NULL COMMENT '输出JSON Schema',
  enabled_flag CHAR(1) NOT NULL DEFAULT '1',
  create_by VARCHAR(64) DEFAULT '',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64) DEFAULT '',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  del_flag CHAR(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (template_id),
  UNIQUE KEY uk_prompt_template_version (template_code, version_no, del_flag),
  KEY idx_prompt_task_enabled (task_type, enabled_flag)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI视频提示词模板';

CREATE TABLE IF NOT EXISTS ai_video_generation_task (
  task_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '任务ID',
  project_id BIGINT NOT NULL COMMENT '项目ID',
  chapter_id BIGINT DEFAULT NULL COMMENT '章节ID',
  scene_id BIGINT DEFAULT NULL COMMENT '场景ID',
  shot_id BIGINT DEFAULT NULL COMMENT '镜头ID',
  asset_id BIGINT DEFAULT NULL COMMENT '目标资产ID',
  parent_task_id BIGINT DEFAULT NULL COMMENT '父任务ID',
  task_type VARCHAR(64) NOT NULL COMMENT 'PARSE/STORY_BIBLE/ASSET_PLAN/IMAGE/VIDEO/VOICE/QUALITY/RENDER',
  task_name VARCHAR(255) NOT NULL COMMENT '任务名称',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/QUEUED/RUNNING/WAITING_CALLBACK/QUALITY_CHECK/SUCCEEDED/FAILED/RETRYING/NEEDS_REVIEW/CANCELED',
  priority INT NOT NULL DEFAULT 100 COMMENT '优先级，数值小优先',
  idempotency_key VARCHAR(128) NOT NULL COMMENT '幂等键',
  provider_code VARCHAR(64) DEFAULT NULL COMMENT '供应商',
  model_code VARCHAR(128) DEFAULT NULL COMMENT '模型',
  provider_task_id VARCHAR(255) DEFAULT NULL COMMENT '供应商任务ID',
  request_json JSON DEFAULT NULL COMMENT '脱敏后的请求参数',
  response_json JSON DEFAULT NULL COMMENT '供应商原始响应',
  progress TINYINT NOT NULL DEFAULT 0 COMMENT '进度0-100',
  retry_count INT NOT NULL DEFAULT 0 COMMENT '已重试次数',
  max_retry INT NOT NULL DEFAULT 3 COMMENT '最大重试次数',
  next_retry_time DATETIME DEFAULT NULL COMMENT '下次重试时间',
  error_code VARCHAR(128) DEFAULT NULL COMMENT '错误码',
  error_message TEXT DEFAULT NULL COMMENT '错误信息',
  estimated_cost DECIMAL(12,4) NOT NULL DEFAULT 0 COMMENT '预估成本',
  actual_cost DECIMAL(12,4) NOT NULL DEFAULT 0 COMMENT '实际成本',
  callback_event_id VARCHAR(255) DEFAULT NULL COMMENT '最后回调事件ID',
  started_time DATETIME DEFAULT NULL,
  completed_time DATETIME DEFAULT NULL,
  version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  create_by VARCHAR(64) DEFAULT '',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64) DEFAULT '',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  del_flag CHAR(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (task_id),
  UNIQUE KEY uk_task_idempotency (idempotency_key, del_flag),
  KEY idx_task_schedule (status, priority, next_retry_time),
  KEY idx_task_provider (provider_code, provider_task_id),
  KEY idx_task_project_chapter (project_id, chapter_id),
  KEY idx_task_asset (asset_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI视频异步生成任务';

CREATE TABLE IF NOT EXISTS ai_video_quality_report (
  report_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '质检报告ID',
  project_id BIGINT NOT NULL COMMENT '项目ID',
  task_id BIGINT DEFAULT NULL COMMENT '任务ID',
  asset_id BIGINT DEFAULT NULL COMMENT '资产ID',
  check_type VARCHAR(64) NOT NULL COMMENT 'CONTENT/CONSISTENCY/TECHNICAL/STORY',
  checker_code VARCHAR(128) NOT NULL COMMENT '检查器或模型编码',
  status VARCHAR(32) NOT NULL COMMENT 'PASSED/WARNING/FAILED',
  overall_score DECIMAL(5,4) DEFAULT NULL COMMENT '总分0-1',
  metric_json JSON DEFAULT NULL COMMENT '各指标评分',
  issue_json JSON DEFAULT NULL COMMENT '问题列表',
  suggested_action VARCHAR(64) DEFAULT NULL COMMENT 'APPROVE/REGENERATE/NEEDS_REVIEW/BLOCK',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (report_id),
  KEY idx_quality_asset (asset_id, create_time),
  KEY idx_quality_task (task_id),
  KEY idx_quality_project_status (project_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI视频质量报告';

CREATE TABLE IF NOT EXISTS ai_video_render (
  render_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '渲染ID',
  project_id BIGINT NOT NULL COMMENT '项目ID',
  chapter_id BIGINT DEFAULT NULL COMMENT '章节ID',
  render_name VARCHAR(255) NOT NULL COMMENT '成片名称',
  render_type VARCHAR(32) NOT NULL COMMENT 'CHAPTER/PROJECT/TRAILER',
  aspect_ratio VARCHAR(16) NOT NULL DEFAULT '16:9',
  resolution VARCHAR(32) DEFAULT NULL COMMENT '分辨率',
  timeline_json JSON NOT NULL COMMENT '镜头、音频、字幕时间线',
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/QUEUED/RUNNING/SUCCEEDED/FAILED',
  output_asset_id BIGINT DEFAULT NULL COMMENT '最终视频资产ID',
  task_id BIGINT DEFAULT NULL COMMENT '关联渲染任务',
  version_no INT NOT NULL DEFAULT 1,
  create_by VARCHAR(64) DEFAULT '',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_by VARCHAR(64) DEFAULT '',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  del_flag CHAR(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (render_id),
  KEY idx_render_project_chapter (project_id, chapter_id),
  KEY idx_render_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI视频成片渲染';

CREATE TABLE IF NOT EXISTS ai_video_task_outbox (
  outbox_id BIGINT NOT NULL AUTO_INCREMENT COMMENT 'Outbox ID',
  task_id BIGINT NOT NULL COMMENT '任务ID',
  event_type VARCHAR(64) NOT NULL COMMENT 'TASK_CREATED/TASK_RETRY/ASSET_APPROVED',
  payload_json JSON NOT NULL COMMENT '投递负载',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/SENT/FAILED',
  retry_count INT NOT NULL DEFAULT 0,
  next_retry_time DATETIME DEFAULT NULL,
  sent_time DATETIME DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (outbox_id),
  KEY idx_outbox_dispatch (status, next_retry_time),
  KEY idx_outbox_task (task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI视频任务可靠投递箱';

CREATE TABLE IF NOT EXISTS ai_video_task_attempt (
  attempt_id BIGINT NOT NULL AUTO_INCREMENT COMMENT '尝试ID',
  task_id BIGINT NOT NULL COMMENT '任务ID',
  attempt_no INT NOT NULL COMMENT '尝试序号，从1开始递增',
  status VARCHAR(32) NOT NULL DEFAULT 'SUBMITTED' COMMENT 'SUBMITTED/SUCCEEDED/FAILED',
  provider_code VARCHAR(64) DEFAULT NULL COMMENT '供应商',
  model_code VARCHAR(128) DEFAULT NULL COMMENT '模型',
  provider_request_id VARCHAR(255) DEFAULT NULL COMMENT '供应商请求标识（提交幂等键）',
  provider_task_id VARCHAR(255) DEFAULT NULL COMMENT '供应商任务ID（异步查询/回调关联）',
  error_code VARCHAR(128) DEFAULT NULL COMMENT '错误分类码',
  error_message TEXT DEFAULT NULL COMMENT '错误信息',
  started_time DATETIME DEFAULT NULL COMMENT '尝试开始时间',
  completed_time DATETIME DEFAULT NULL COMMENT '尝试结束时间',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (attempt_id),
  UNIQUE KEY uk_attempt_task_no (task_id, attempt_no),
  KEY idx_attempt_provider (provider_code, provider_task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI视频生成任务尝试记录';
