[package]
name = "lingxi-ai-platform"
version = "1.0.1"
description = "LingXi Intelligent Application Platform"
authors = ["LingXi"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-updater = "2"
serde_json = "1"
